name: theeco
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: 4.6.6
  flutter: 
    sdk: flutter
  shimmer: ^3.0.0
  pretty_json:
    git:
      url: https://github.com/asimsharf/pretty_json.git
  either_dart: ^1.0.0
  mockito: ^5.4.4
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_screenutil: ^5.9.3
  flutter_sound: ^9.2.14
  path_provider: ^2.1.4
  auto_size_text: ^3.0.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.9

flutter: 
  uses-material-design: true

  fonts:
    - family: din_next_tl_arabic_regular
      fonts:
        - asset: assets/fonts/din_next_tl_arabic_regular.ttf
    - family: ping
      fonts:
        - asset: assets/fonts/ping/ping_black.otf
        - asset: assets/fonts/ping/ping_bold.otf
        - asset: assets/fonts/ping/ping_extra_light.otf
        - asset: assets/fonts/ping/ping_hair_line.otf
        - asset: assets/fonts/ping/ping_heavy.otf
        - asset: assets/fonts/ping/ping_light.otf
        - asset: assets/fonts/ping/ping_medium.otf
        - asset: assets/fonts/ping/ping_regular.otf
        - asset: assets/fonts/ping/ping_thin.otf
